config/routes.rb
Chart::Application.routes.draw do
  

  root :to => "seats#index" 
  resources :seats 
  resources :chats
  resources :users
  resource :session  
    
  match '/login' => "sessions#new", :as => "login"
  match '/logout' => "sessions#destroy", :as => "logout"

end

app/models/chat.rb
class Chat < ActiveRecord::Base
end

app/models/seat.rb
class Seat < ActiveRecord::Base
  belongs_to :user 
  
  
end

app/models/user.rb
require 'digest'
class User < ActiveRecord::Base
  attr_accessor :password
  
  validates :email, :uniqueness => true, 
                    :length => { :within => 5..50 }, 
                    :format => { :with => /^[^@][\w.-]+@[\w.-]+[.][a-z]{2,4}$/i }
  validates :password, :confirmation => true,
                       :length => { :within => 4..20 },
                       :presence => true,
                       :if => :password_required?

  has_one :profile
  has_many :articles, :order => 'published_at DESC, title ASC',
                      :dependent => :nullify
  has_many :replies, :through => :articles, :source => :comments

  before_save :encrypt_new_password

  def self.authenticate(email, password)
    user = find_by_email(email)
    return user if user && user.authenticated?(password)
  end

  def authenticated?(password)
    self.hashed_password == encrypt(password)
  end

  protected
    def encrypt_new_password
      return if password.blank?
      self.hashed_password = encrypt(password)
    end

    def password_required?
      hashed_password.blank? || password.present?
    end

    def encrypt(string)
      Digest::SHA1.hexdigest(string)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery


  protected
    # Returns the currently logged in user or nil if there isn't one
    def current_user
      return unless session[:user_id]
      @current_user ||= User.find_by_id(session[:user_id])
    end

    # Make current_user available in templates as a helper
    helper_method :current_user

    # Filter method to enforce a login requirement
    # Apply as a before_filter on any controller you want to protect
    def authenticate
      logged_in? ? true : access_denied
    end

    # Predicate method to test for a logged in user
    def logged_in?
      current_user.is_a? User

end

    # Make logged_in? available in templates as a helper
    helper_method :logged_in?

    def access_denied
      redirect_to login_path, :notice => "Please log in to continue" and return false
    end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController


  # GET /chats
  # GET /chats.xml
  def index
    @chats = Chat.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @chats }
    end
  end

  # GET /chats/1
  # GET /chats/1.xml
  def show
    @chat = Chat.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @chat }
    end
  end

  # GET /chats/new
  # GET /chats/new.xml
  def new
    @chat = Chat.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @chat }
    end
  end

  # GET /chats/1/edit
  def edit
    @chat = Chat.find(params[:id])
  end

  # POST /chats
  # POST /chats.xml
  def create
    @chat = Chat.new(params[:chat])
    if @chat.save
    respond_to do |format|
        format.html { redirect_to(@chat, :notice => 'Chat was successfully created.') }
        format.xml  { render :xml => @chat, :status => :created, :location => @chat }
        format.js
      end
      else
        respond_to do |format|
        format.html { render :action => "new" }
        format.xml  { render :xml => @chat.errors, :status => :unprocessable_entity }
        format.js
      end
    end
  end

  # PUT /chats/1
  # PUT /chats/1.xml
  def update
    @chat = Chat.find(params[:id])

    respond_to do |format|
      if @chat.update_attributes(params[:chat])
        format.html { redirect_to(@chat, :notice => 'Chat was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @chat.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /chats/1
  # DELETE /chats/1.xml
  def destroy
    @chat = Chat.find(params[:id])
    @chat.destroy

    respond_to do |format|
      format.html { redirect_to(chats_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/seats_controller.rb
class SeatsController < ApplicationController

  # GET /seats
  # GET /seats.xml
  def index
    @seats = Seat.all
    @seat = Seat.new

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @seats }
    end
  end

  # GET /seats/1
  # GET /seats/1.xml
  def show
    @seat = Seat.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @seat }
    end
  end

  # GET /seats/new
  # GET /seats/new.xml
  def new
    @seat = Seat.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @seat }
    end
  end

  # GET /seats/1/edit
  def edit
    @seat = Seat.find(params[:id])
    respond_to do |format|
        format.html { redirect_to(@seat, :notice => 'Seat was successfully created.') }
        format.js
    end
  end

  # POST /seats
  # POST /seats.xml
  def create
    @seat = Seat.new(params[:seat])
    if @seat.save
    respond_to do |format|
        format.html { redirect_to(@seat, :notice => 'Seat was successfully created.') }
        format.xml  { render :xml => @seat, :status => :created, :location => @seat }
        format.js
      end
      else
        respond_to do |format|
        format.html { render :action => "new" }
        format.xml  { render :xml => @seat.errors, :status => :unprocessable_entity }
        format.js
      end
    end
  end

  # PUT /seats/1
  # PUT /seats/1.xml
  def update
    @seat = Seat.find(params[:id])
	
	#@user = current_user
#if !(@seat.user_id == @user.id)

    respond_to do |format|
      if @seat.update_attributes(params[:seat])
        format.html { redirect_to(@seat, :notice => 'Seat was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @seat.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /seats/1
  # DELETE /seats/1.xml
  def destroy
    @seat = Seat.find(params[:id])
    @seat.destroy

    respond_to do |format|
      format.html { redirect_to(seats_url) }
      format.xml  { head :ok }
      format.js
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    if user = User.authenticate(params[:email], params[:password])
      session[:user_id] = user.id
      redirect_to seats_path, :notice => "Logged in successfully"
    else
      flash.now[:alert] = "Invalid login/password combination"
      render :action => 'new'
    end
  end
  
  def destroy
    reset_session
    redirect_to seats_path, :notice => "You successfully logged out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate, :only => [:edit, :update]
  
  def new
    @user = User.new
  end
  
  def show
	@user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to seats_path, :notice => 'User successfully added.'
    else
      render :action => 'new'
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update_attributes(params[:user])
      redirect_to seats_path, :notice => 'Updated user information successfully.'
    else
      render :action => 'edit'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/seats_helper.rb
module SeatsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chats/_chat.html.erb
<%= div_for chat do %>
    <strong> <%= chat.name %></strong>:   
  <%= chat.message %>
<% end %>

app/views/chats/_form.html.erb
<%= form_for(@chat) do |f| %>
  <% if @chat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chat.errors.count, "error") %> prohibited this chat from being saved:</h2>

      <ul>
      <% @chat.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

Your email:   <%= current_user.email%>
<br />
Your user id: <%= current_user.id%>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_area :message %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chats/create.js.erb
$('#chats').append("<%= escape_javascript(render(@chat)) %>");
$('#new_chat')[0].reset();

app/views/chats/edit.html.erb
<h1>Editing chat</h1>

<%= render 'form' %>

<%= link_to 'Show', @chat %> |
<%= link_to 'Back', chats_path %>

app/views/chats/fail_create.js.erb
alert("<%= @chat.errors.full_messages.to_sentence %>");

app/views/chats/index.html.erb
<h1>Listing chats</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  
<div id = "chats">
  <%= render @chats %>
</div>

</table>


<%= render :file => 'chats/new' %>

<br />

<%= link_to 'Back', seats_path %>

app/views/chats/new.html.erb
<%= form_for (:chat, :remote => true) do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_area :message %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chats/new.js.erb
$("<%= escape_javascript render(:file => 'chats/new.html.erb') %>").insertAfter('#chats');
$('#new_chat_link').hide();

app/views/chats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @chat.name %>
</p>

<p>
  <b>Message:</b>
  <%= @chat.message %>
</p>


<%= link_to 'Edit', edit_chat_path(@chat) %> |
<%= link_to 'Back', chats_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chart</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag 'jquery-1.4.2.min', 'rails', 'application' %>
  <%= csrf_meta_tag %>
</head>
<body>


<%= content_tag :p, notice, :class => 'notice' if notice.present? %>
<%= content_tag :p, alert, :class => 'alert' if alert.present? %>


<%= yield %>

</body>
</html>

app/views/seats/_form.html.erb
<%= form_for(@seat) do |f| %>
  <% if @seat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@seat.errors.count, "error") %> prohibited this seat from being saved:</h2>

      <ul>
      <% @seat.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  
  <div class="field">
    <%= f.label :user_id %> id<br />
    <%= f.text_field :user_id %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/seats/_seat.html.erb
<%= div_for seat do %>
<table>
   <tr> 
	<td><strong>Location: </strong> <%= seat.location %></td>	<td><strong>User: </strong> <%= seat.user_id %></td>
    <td>
	<td>
	<td>
	<td>
	<span class='actions'>
      <td><%= link_to "Edit", edit_seat_path(seat), :remote => true %></td>
      <td><%= link_to "Delete", seat, :confirm => "Are you sure?",:method => :delete, :remote => true %></td>
    </span> 
	</td>
   </tr>
</table>

<% end %>

app/views/seats/create.js.erb
$('#seats').append("<%= escape_javascript(render(@seat)) %>");
$('#new_seat')[0].reset();

app/views/seats/destroy.js.erb
$("#<%= dom_id(@seat) %>").remove()

app/views/seats/edit.html.erb
<h3>Editing seat</h3>
<%= render @seat%>
<br />
<%= link_to 'Back', seats_path %>
<br />
<br />
<br />
<br />

app/views/seats/edit.js.erb
$("<%= escape_javascript render(:file => 'seats/edit.html.erb') %>").insertAfter('#seats');
$('#edit_seat_link').hide();

app/views/seats/index.html.erb
<h1>Seating Chart</h1>

<%= link_to 'New User', new_user_path %>
<%= link_to 'Login', "login" %>
<%= link_to 'Logout', "logout" %>

<br />
<br />
<table border="1">
<tr>
<th>3A </th> 
<th>4A </th>
<th> </th>  
<th>5A </th> 
<th>6A </th> 
</tr>

<tr>
<th>7B </th> 
<th>8B </th>
<th> </th>  
<th>9B </th> 
<th>10B </th>  
</tr>

<tr>
<th>11C </th> 
<th>12C </th>
<th>  </th>  
<th>13C </th> 
<th>14C </th>  
</tr>

<tr>
<th>15D </th> 
<th>16D </th>
<th> </th>  
<th>17D </th> 
<th>18D </th>  
</tr>

</table>
<br />

<br />
<td><%= link_to 'Chat', "chats" %></td>
<br />
<table>
  <tr>
    <th></th>
    <th></th>
  </tr>


</table>
<br />

<div id = "seats">
  <%= render @seats %>
</div>

<%= render :file => 'seats/new' %>


<br />

app/views/seats/new.html.erb
<%= form_for(@seat, :remote => true) do |f| %>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  
  <div class="field">
    <%= f.label :user_id %> id<br />
    <%= f.text_field :user_id %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/seats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Location:</b>
  <%= @seat.location %>
  <br />
  <b>User:</b>
  <%= @seat.user_id%>
  <br />
  <b>User:</b>
  <%= @seat.user.email%>
</p>


<%= link_to 'Edit', edit_seat_path(@seat) %> |
<%= link_to 'Back', seats_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@user.errors.count, "error") %>
prohibited this user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  
  <div class="field>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>

  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/create.js.erb
$('#comments').append("<%= escape_javascript(render(@comment)) %>");
$('#new_comment')[0].reset();

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Back', seats_path %> 

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', seats_path %>

app/views/users/show.html.erb
<p>
  <b>User:</b>
  <%= @user.email %>

</p>



<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', seats_path %>